### Importing the libraries

In [17]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [18]:
tf.__version__

'2.4.1'

### Data Preprocessing

#### Importing the dataset

In [53]:
dataset = pd.read_csv('/content/drive/MyDrive/Deep learning/Artificial Neural Network/Dataset/Churn_Modelling.csv')
dataset.shape

(10000, 14)

In [20]:
X = dataset.iloc[:, 3:-1].values
Y = dataset.iloc[:, -1].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

#### Encoding categorical variables

In [21]:
from sklearn.preprocessing import LabelEncoder
labelen = LabelEncoder()
X[:, 1] = labelen.fit_transform(X[:, 1])
X[:, 2] = labelen.fit_transform(X[:, 2])

In [22]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

#### Spliting the dataset

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 40)

#### Feature scaling

In [24]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [25]:
X_train

array([[ 0.23032791,  0.30981935, -1.09003844, ..., -1.55337352,
         0.97067965, -0.70848497],
       [ 0.54015481, -0.89923178,  0.91739884, ...,  0.64376017,
        -1.030206  , -1.38762036],
       [ 0.46786187,  0.30981935,  0.91739884, ..., -1.55337352,
         0.97067965, -0.83538323],
       ...,
       [ 0.70539583,  1.51887049, -1.09003844, ...,  0.64376017,
        -1.030206  , -1.3983009 ],
       [-0.15179195,  1.51887049, -1.09003844, ...,  0.64376017,
        -1.030206  , -0.99538194],
       [ 0.45753431,  1.51887049, -1.09003844, ..., -1.55337352,
         0.97067965, -1.5031824 ]])

### Building the ANN

 Initilizing the ANN

In [26]:
ann = tf.keras.models.Sequential()


 Input layer and first hidden layer

In [27]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu' ))

 second hidden layer

In [28]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


Adding output layer

In [29]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Training the ANN

compile the ANN

In [30]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

Train ANN

In [ ]:
ann.fit(X_train, Y_train, batch_size=32, epochs=100)

predicting the test set result

In [46]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test), 1)), 1))

[[0 1]
 [0 0]
 [0 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


cunfusioin matrix and accuracy of matrix

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred)

[[1537   79]
 [ 173  211]]


0.874

In [51]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(X_train, Y_train)
Y_pred_LR = LR.predict(X_test)
print(Y_pred_LR)

[0 0 0 ... 0 0 0]


In [52]:
accuracy_score(Y_test, Y_pred_LR)

0.8195